package wddbyui.cit260.hangman.frames;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import wddbyui.cit260.hangman.enums.Status;
import wddbyui.cit260.hangman.menus.MainMenuControl;
import wddbyui.cit260.hangman.words.MysteryWord;

/**
 *
 * @author Lorna
 */
public class GameFrame extends javax.swing.JFrame implements Serializable {
    
    private MysteryWord mysteryWord;
    private MainMenuControl mainMenuControl = new MainMenuControl();
    private Gallows gallows = new Gallows();

    private Status status;
    private char mysteryLetter;
    private static String gallowsString = "";

    /**
     * Creates new form GameFrame
     */
    public GameFrame() throws IOException {
        this.setStatus(Status.PLAYING);
        
        this.mysteryWord = new MysteryWord();
        initComponents();
        
        if (!GetNamesFrame.getNameOfPlayer().isEmpty()) {
            this.jGuessWordLabel.setText(GetNamesFrame.getNameOfPlayer() + ", guess this word:");
        }
        
        this.jMysteryWordDisplayLabel.setText(mysteryWord.displayMysteryWord('_'));
        gallows.displayGallows('6');
        this.jGallowsArea.setText(gallowsString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHangmanPanel = new javax.swing.JPanel();
        jpTitle = new javax.swing.JLabel();
        jExitButton = new javax.swing.JButton();
        jpInstructionsButton = new javax.swing.JButton();
        jRemainingLettersLabel = new javax.swing.JLabel();
        jMysteryWordDisplayLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGallowsArea = new javax.swing.JTextArea();
        jGuessWordLabel = new javax.swing.JLabel();
        jAButton = new javax.swing.JButton();
        jBButton = new javax.swing.JButton();
        jCButton = new javax.swing.JButton();
        jDButton = new javax.swing.JButton();
        jEButton = new javax.swing.JButton();
        jFButton = new javax.swing.JButton();
        jGButton = new javax.swing.JButton();
        jHButton = new javax.swing.JButton();
        jIButton = new javax.swing.JButton();
        jJButton = new javax.swing.JButton();
        jKButton = new javax.swing.JButton();
        jLButton = new javax.swing.JButton();
        jMButton = new javax.swing.JButton();
        jNButton = new javax.swing.JButton();
        jOButton = new javax.swing.JButton();
        jPButton = new javax.swing.JButton();
        jQButton = new javax.swing.JButton();
        jRButton = new javax.swing.JButton();
        jSButton = new javax.swing.JButton();
        jTButton = new javax.swing.JButton();
        jUButton = new javax.swing.JButton();
        jVButton = new javax.swing.JButton();
        jWButton = new javax.swing.JButton();
        jXButton = new javax.swing.JButton();
        jYButton = new javax.swing.JButton();
        jAButton24 = new javax.swing.JButton();
        jGuessesLeftLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jHangmanPanel.setBackground(new java.awt.Color(204, 204, 255));

        jpTitle.setFont(new java.awt.Font("Minion Pro SmBd", 0, 36)); // NOI18N
        jpTitle.setForeground(new java.awt.Color(61, 61, 155));
        jpTitle.setText("Hangman");
        jpTitle.setName("jpTitle"); // NOI18N

        jExitButton.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        jExitButton.setText("Exit Game");
        jExitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jpInstructionsButton.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        jpInstructionsButton.setText("Display Instructions");
        jpInstructionsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpInstructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpInstructionsButtonActionPerformed(evt);
            }
        });

        jRemainingLettersLabel.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
        jRemainingLettersLabel.setText("Choose a letter:");

        jMysteryWordDisplayLabel.setBackground(new java.awt.Color(255, 247, 222));
        jMysteryWordDisplayLabel.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jMysteryWordDisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMysteryWordDisplayLabel.setText("word");
        jMysteryWordDisplayLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 166), 2));

        jGallowsArea.setEditable(false);
        jGallowsArea.setBackground(new java.awt.Color(255, 247, 222));
        jGallowsArea.setColumns(20);
        jGallowsArea.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jGallowsArea.setForeground(jpTitle.getForeground());
        jGallowsArea.setRows(5);
        jGallowsArea.setText("                       ______________\n                       |                              |\n                       |                              |\n                       |                              |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n         ______|______________\n   ___|                                             |\n    |                                                   | ");
        jGallowsArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 166), 3));
        jScrollPane1.setViewportView(jGallowsArea);

        jGuessWordLabel.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
        jGuessWordLabel.setText("Guess this word:");

        jAButton.setBackground(new java.awt.Color(204, 204, 255));
        jAButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jAButton.setText("A");
        jAButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAButtonActionPerformed(evt);
            }
        });

        jBButton.setBackground(new java.awt.Color(204, 204, 255));
        jBButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jBButton.setText("B");
        jBButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jBButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBButtonActionPerformed(evt);
            }
        });

        jCButton.setBackground(new java.awt.Color(204, 204, 255));
        jCButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jCButton.setText("C");
        jCButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCButtonActionPerformed(evt);
            }
        });

        jDButton.setBackground(new java.awt.Color(204, 204, 255));
        jDButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jDButton.setText("D");
        jDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDButtonActionPerformed(evt);
            }
        });

        jEButton.setBackground(new java.awt.Color(204, 204, 255));
        jEButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jEButton.setText("E");
        jEButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jEButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEButtonActionPerformed(evt);
            }
        });

        jFButton.setBackground(new java.awt.Color(204, 204, 255));
        jFButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jFButton.setText("F");
        jFButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jFButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFButtonActionPerformed(evt);
            }
        });

        jGButton.setBackground(new java.awt.Color(204, 204, 255));
        jGButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jGButton.setText("G");
        jGButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jGButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jGButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGButtonActionPerformed(evt);
            }
        });

        jHButton.setBackground(new java.awt.Color(204, 204, 255));
        jHButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jHButton.setText("H");
        jHButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jHButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jHButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHButtonActionPerformed(evt);
            }
        });

        jIButton.setBackground(new java.awt.Color(204, 204, 255));
        jIButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jIButton.setText("I");
        jIButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jIButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIButtonActionPerformed(evt);
            }
        });

        jJButton.setBackground(new java.awt.Color(204, 204, 255));
        jJButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jJButton.setText("J");
        jJButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jJButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJButtonActionPerformed(evt);
            }
        });

        jKButton.setBackground(new java.awt.Color(204, 204, 255));
        jKButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jKButton.setText("K");
        jKButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jKButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKButtonActionPerformed(evt);
            }
        });

        jLButton.setBackground(new java.awt.Color(204, 204, 255));
        jLButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLButton.setText("L");
        jLButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLButtonActionPerformed(evt);
            }
        });

        jMButton.setBackground(new java.awt.Color(204, 204, 255));
        jMButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jMButton.setText("M");
        jMButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMButtonActionPerformed(evt);
            }
        });

        jNButton.setBackground(new java.awt.Color(204, 204, 255));
        jNButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jNButton.setText("N");
        jNButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jNButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNButtonActionPerformed(evt);
            }
        });

        jOButton.setBackground(new java.awt.Color(204, 204, 255));
        jOButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jOButton.setText("O");
        jOButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jOButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOButtonActionPerformed(evt);
            }
        });

        jPButton.setBackground(new java.awt.Color(204, 204, 255));
        jPButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jPButton.setText("P");
        jPButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPButtonActionPerformed(evt);
            }
        });

        jQButton.setBackground(new java.awt.Color(204, 204, 255));
        jQButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jQButton.setText("Q");
        jQButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jQButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQButtonActionPerformed(evt);
            }
        });

        jRButton.setBackground(new java.awt.Color(204, 204, 255));
        jRButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jRButton.setText("R");
        jRButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRButtonActionPerformed(evt);
            }
        });

        jSButton.setBackground(new java.awt.Color(204, 204, 255));
        jSButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jSButton.setText("S");
        jSButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSButtonActionPerformed(evt);
            }
        });

        jTButton.setBackground(new java.awt.Color(204, 204, 255));
        jTButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jTButton.setText("T");
        jTButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTButtonActionPerformed(evt);
            }
        });

        jUButton.setBackground(new java.awt.Color(204, 204, 255));
        jUButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jUButton.setText("U");
        jUButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jUButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jUButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUButtonActionPerformed(evt);
            }
        });

        jVButton.setBackground(new java.awt.Color(204, 204, 255));
        jVButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jVButton.setText("V");
        jVButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jVButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVButtonActionPerformed(evt);
            }
        });

        jWButton.setBackground(new java.awt.Color(204, 204, 255));
        jWButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jWButton.setText("W");
        jWButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jWButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWButtonActionPerformed(evt);
            }
        });

        jXButton.setBackground(new java.awt.Color(204, 204, 255));
        jXButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jXButton.setText("X");
        jXButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jXButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jXButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButtonActionPerformed(evt);
            }
        });

        jYButton.setBackground(new java.awt.Color(204, 204, 255));
        jYButton.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jYButton.setText("Y");
        jYButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jYButton.setPreferredSize(new java.awt.Dimension(50, 30));
        jYButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYButtonActionPerformed(evt);
            }
        });

        jAButton24.setBackground(new java.awt.Color(204, 204, 255));
        jAButton24.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jAButton24.setText("Z");
        jAButton24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAButton24.setPreferredSize(new java.awt.Dimension(50, 30));
        jAButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAButton24ActionPerformed(evt);
            }
        });

        jGuessesLeftLabel.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
        jGuessesLeftLabel.setText("You have 6 guesses left");

        javax.swing.GroupLayout jHangmanPanelLayout = new javax.swing.GroupLayout(jHangmanPanel);
        jHangmanPanel.setLayout(jHangmanPanelLayout);
        jHangmanPanelLayout.setHorizontalGroup(
            jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jHangmanPanelLayout.createSequentialGroup()
                .addGroup(jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHangmanPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jHangmanPanelLayout.createSequentialGroup()
                                .addComponent(jAButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jHangmanPanelLayout.createSequentialGroup()
                                .addGroup(jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jHangmanPanelLayout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(jpTitle))
                                    .addComponent(jpInstructionsButton)
                                    .addComponent(jGuessWordLabel)
                                    .addComponent(jMysteryWordDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jGuessesLeftLabel))
                                .addGap(59, 59, 59)))
                        .addGroup(jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jHangmanPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jHButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jIButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jHangmanPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jNButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jQButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jHangmanPanelLayout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jExitButton))
                    .addGroup(jHangmanPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRemainingLettersLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jHangmanPanelLayout.setVerticalGroup(
            jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jHangmanPanelLayout.createSequentialGroup()
                .addGroup(jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jHangmanPanelLayout.createSequentialGroup()
                        .addComponent(jpTitle)
                        .addGap(23, 23, 23)
                        .addComponent(jpInstructionsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jGuessWordLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jMysteryWordDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jGuessesLeftLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jRemainingLettersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jHangmanPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jJButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jHangmanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jQButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jVButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHangmanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jHangmanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpInstructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpInstructionsButtonActionPerformed
        this.setStatus(Status.INSTRUCTIONS);
        mainMenuControl.activateControl(status);
    }//GEN-LAST:event_jpInstructionsButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.setStatus(Status.EXIT);
        mainMenuControl.activateControl(status);
        this.dispose(); //exit the game
    }//GEN-LAST:event_jExitButtonActionPerformed

    private void jAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAButtonActionPerformed
        mysteryLetter = this.jAButton.getText().charAt(0);
        this.jAButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jAButtonActionPerformed

    private void jBButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBButtonActionPerformed
        mysteryLetter = this.jBButton.getText().charAt(0);
        this.jBButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jBButtonActionPerformed

    private void jCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCButtonActionPerformed
        mysteryLetter = this.jCButton.getText().charAt(0);
        this.jCButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jCButtonActionPerformed

    private void jDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDButtonActionPerformed
        mysteryLetter = this.jDButton.getText().charAt(0);
        this.jDButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jDButtonActionPerformed

    private void jEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEButtonActionPerformed
        mysteryLetter = this.jEButton.getText().charAt(0);
        this.jEButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jEButtonActionPerformed

    private void jFButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFButtonActionPerformed
        mysteryLetter = this.jFButton.getText().charAt(0);
        this.jFButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jFButtonActionPerformed

    private void jGButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGButtonActionPerformed
        mysteryLetter = this.jGButton.getText().charAt(0);
        this.jGButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jGButtonActionPerformed

    private void jHButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHButtonActionPerformed
        mysteryLetter = this.jHButton.getText().charAt(0);
        this.jHButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jHButtonActionPerformed

    private void jIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIButtonActionPerformed
        mysteryLetter = this.jIButton.getText().charAt(0);
        this.jIButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jIButtonActionPerformed

    private void jJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJButtonActionPerformed
        mysteryLetter = this.jJButton.getText().charAt(0);
        this.jJButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jJButtonActionPerformed

    private void jKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKButtonActionPerformed
        mysteryLetter = this.jKButton.getText().charAt(0);
        this.jKButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jKButtonActionPerformed

    private void jLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLButtonActionPerformed
        mysteryLetter = this.jLButton.getText().charAt(0);
        this.jLButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jLButtonActionPerformed

    private void jMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMButtonActionPerformed
        mysteryLetter = this.jMButton.getText().charAt(0);
        this.jMButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jMButtonActionPerformed

    private void jNButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNButtonActionPerformed
        mysteryLetter = this.jNButton.getText().charAt(0);
        this.jNButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jNButtonActionPerformed

    private void jOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOButtonActionPerformed
        mysteryLetter = this.jOButton.getText().charAt(0);
        this.jOButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jOButtonActionPerformed

    private void jPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPButtonActionPerformed
        mysteryLetter = this.jPButton.getText().charAt(0);
        this.jPButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jPButtonActionPerformed

    private void jQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQButtonActionPerformed
        mysteryLetter = this.jQButton.getText().charAt(0);
        this.jQButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jQButtonActionPerformed

    private void jRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRButtonActionPerformed
        mysteryLetter = this.jRButton.getText().charAt(0);
        this.jRButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jRButtonActionPerformed

    private void jSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSButtonActionPerformed
        mysteryLetter = this.jSButton.getText().charAt(0);
        this.jSButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jSButtonActionPerformed

    private void jTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTButtonActionPerformed
        mysteryLetter = this.jTButton.getText().charAt(0);
        this.jTButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jTButtonActionPerformed

    private void jUButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUButtonActionPerformed
        mysteryLetter = this.jUButton.getText().charAt(0);
        this.jUButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jUButtonActionPerformed

    private void jVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVButtonActionPerformed
        mysteryLetter = this.jVButton.getText().charAt(0);
        this.jVButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jVButtonActionPerformed

    private void jWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWButtonActionPerformed
        mysteryLetter = this.jWButton.getText().charAt(0);
        this.jWButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jWButtonActionPerformed

    private void jXButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButtonActionPerformed
        mysteryLetter = this.jXButton.getText().charAt(0);
        this.jXButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jXButtonActionPerformed

    private void jYButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYButtonActionPerformed
        mysteryLetter = this.jYButton.getText().charAt(0);
        this.jYButton.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jYButtonActionPerformed

    private void jAButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAButton24ActionPerformed
        mysteryLetter = this.jAButton24.getText().charAt(0);
        this.jAButton24.setText("_");
        this.playTheGame();
    }//GEN-LAST:event_jAButton24ActionPerformed

    private void playTheGame() {
        //mysteryLetter = this.jLetterInputField.getText().charAt(0);
        mysteryLetter = Character.toLowerCase(mysteryLetter);
        this.jMysteryWordDisplayLabel.setText(mysteryWord.displayMysteryWord(mysteryLetter));
        //alphabet.setLetter(mysteryLetter);
        //this.jAlphabetLabel.setText(alphabet.displayArray());
        //this.jLetterInputField.setText("");
        gallows.displayGallows(mysteryWord.getNumberOfGuesses());
        this.jGallowsArea.setText(gallowsString);
        this.jGuessesLeftLabel.setText("You have " + mysteryWord.getNumberOfGuesses() + " guesses left.");
        this.setStatus(mysteryWord.winOrLose());
        
        if (this.getStatus() == Status.WIN_GAME){
            displayWinningMessage();
        }
        else {
            if (this.getStatus() == Status.LOSE_GAME) {
                gallows.displayGallows(mysteryWord.getNumberOfGuesses());
                displayLosingMessage();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new GameFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GameFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAButton;
    private javax.swing.JButton jAButton24;
    private javax.swing.JButton jBButton;
    private javax.swing.JButton jCButton;
    private javax.swing.JButton jDButton;
    private javax.swing.JButton jEButton;
    private javax.swing.JButton jExitButton;
    private javax.swing.JButton jFButton;
    private javax.swing.JButton jGButton;
    private javax.swing.JTextArea jGallowsArea;
    private javax.swing.JLabel jGuessWordLabel;
    private javax.swing.JLabel jGuessesLeftLabel;
    private javax.swing.JButton jHButton;
    private javax.swing.JPanel jHangmanPanel;
    private javax.swing.JButton jIButton;
    private javax.swing.JButton jJButton;
    private javax.swing.JButton jKButton;
    private javax.swing.JButton jLButton;
    private javax.swing.JButton jMButton;
    private javax.swing.JLabel jMysteryWordDisplayLabel;
    private javax.swing.JButton jNButton;
    private javax.swing.JButton jOButton;
    private javax.swing.JButton jPButton;
    private javax.swing.JButton jQButton;
    private javax.swing.JButton jRButton;
    private javax.swing.JLabel jRemainingLettersLabel;
    private javax.swing.JButton jSButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jTButton;
    private javax.swing.JButton jUButton;
    private javax.swing.JButton jVButton;
    private javax.swing.JButton jWButton;
    private javax.swing.JButton jXButton;
    private javax.swing.JButton jYButton;
    private javax.swing.JButton jpInstructionsButton;
    private javax.swing.JLabel jpTitle;
    // End of variables declaration//GEN-END:variables

    public Status getStatus() {
        return status;
    }

    private void setStatus(Status status) {
        this.status = status;
    }

    public static String getGallowsString() {
        return gallowsString;
    }

    public static void setGallowsString(String gallowsString) {
        GameFrame.gallowsString = gallowsString;
    }
        
    private void displayWinningMessage() {
        WinGameFrame winGameFrame = new WinGameFrame();
        winGameFrame.setVisible(true);
        this.dispose();
    }

    private void displayLosingMessage() {
        LoseGameFrame loseGameFrame = new LoseGameFrame();
        loseGameFrame.setVisible(true);
        this.dispose();
    }
    
    class Gallows {
            
        private void displayGallows(int gallowsChoice) {  

            switch(gallowsChoice){
                case 6:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t|"
                                   + "\n\t|\t|"
                                   + "\n\t|"
                                   + "\n\t|" 
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                break;
            
                case 5:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t |"
                                   + "\n\t|\t |"
                                   + "\n\t|\t O"
                                   + "\n\t|" 
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                break;
                
                case 4:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t |"
                                   + "\n\t|\t |"
                                   + "\n\t|\t O"
                                   + "\n\t|\t |" 
                                   + "\n\t|\t |"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                break;
            
                case 3:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t |"
                                   + "\n\t|\t |"
                                   + "\n\t|\t O"
                                   + "\n\t|\t/|" 
                                   + "\n\t|\t |"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                break;
            
                case 2:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t |"
                                   + "\n\t|\t |"
                                   + "\n\t|\t O"
                                   + "\n\t|\t/|\\" 
                                   + "\n\t|\t |"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                break;
            
                case 1:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t |"
                                   + "\n\t|\t |"
                                   + "\n\t|\t O"
                                   + "\n\t|\t/|\\" 
                                   + "\n\t|\t |"
                                   + "\n\t|\t/"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                break;
            
                case 0:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t |"
                                   + "\n\t|\t |"
                                   + "\n\t|\t O"
                                   + "\n\t|\t/|\\" 
                                   + "\n\t|\t |"
                                   + "\n\t|\t/ \\"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                break;
            
                default:
                    gallowsString = ("\t______________"
                                   + "\n\t|\t|"
                                   + "\n\t|\t|"
                                   + "\n\t|"
                                   + "\n\t|" 
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|"
                                   + "\n\t|______________"
                                   + "\n\t|\t|"
                                   + "\n");
                }
    }
       
}

}
