/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wddbyui.cit260.hangman.frames;

/**
 *
 * @author Lorna
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpTitle = new javax.swing.JLabel();
        jExitButton = new javax.swing.JButton();
        jpInstructionsButton = new javax.swing.JButton();
        jLetterInputField = new javax.swing.JTextField();
        jEnterLetterLabel = new javax.swing.JLabel();
        jSubmitLetterButton = new javax.swing.JButton();
        jAlphabetLabel = new javax.swing.JLabel();
        jRemainingLettersLabel = new javax.swing.JLabel();
        jMysteryWordDiisplayLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGallowsArea = new javax.swing.JTextArea();
        jGuessWordLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jpTitle.setFont(new java.awt.Font("Minion Pro SmBd", 0, 36)); // NOI18N
        jpTitle.setForeground(new java.awt.Color(61, 61, 155));
        jpTitle.setText("Hangman");
        jpTitle.setName("jpTitle"); // NOI18N

        jExitButton.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        jExitButton.setText("Exit Game");
        jExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButtonActionPerformed(evt);
            }
        });

        jpInstructionsButton.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        jpInstructionsButton.setText("Display Instructions");
        jpInstructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpInstructionsButtonActionPerformed(evt);
            }
        });

        jLetterInputField.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLetterInputField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLetterInputField.setText("W");
        jLetterInputField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 166), 2));

        jEnterLetterLabel.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
        jEnterLetterLabel.setText("Enter your letter choice here:");

        jSubmitLetterButton.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
        jSubmitLetterButton.setText("Submit Letter");

        jAlphabetLabel.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jAlphabetLabel.setText("A B C D E F G H I J K L M N O P Q R S T U V W X Y Z");

        jRemainingLettersLabel.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
        jRemainingLettersLabel.setText("Remaining Letters");

        jMysteryWordDiisplayLabel.setBackground(new java.awt.Color(255, 247, 222));
        jMysteryWordDiisplayLabel.setFont(new java.awt.Font("Myriad Pro", 0, 24)); // NOI18N
        jMysteryWordDiisplayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMysteryWordDiisplayLabel.setText("word");
        jMysteryWordDiisplayLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 166), 2));

        jGallowsArea.setBackground(new java.awt.Color(255, 247, 222));
        jGallowsArea.setColumns(20);
        jGallowsArea.setForeground(jpTitle.getForeground());
        jGallowsArea.setRows(5);
        jGallowsArea.setText("         ______________\n         |            |\n         |            |\n         |            |\n         |\n         |\n         |\n         |\n         |\n         |\n         |\n         |\n         |\n    _____|______________\n ___|                   |\n |                      | ");
        jGallowsArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 166), 3));
        jScrollPane1.setViewportView(jGallowsArea);

        jGuessWordLabel.setFont(new java.awt.Font("Myriad Pro", 0, 16)); // NOI18N
        jGuessWordLabel.setText("Guess This Word:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLetterInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSubmitLetterButton))
                            .addComponent(jpInstructionsButton)
                            .addComponent(jGuessWordLabel)
                            .addComponent(jMysteryWordDiisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEnterLetterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRemainingLettersLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jpTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jAlphabetLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jExitButton)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpTitle)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jpInstructionsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jGuessWordLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jMysteryWordDiisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jEnterLetterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSubmitLetterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jLetterInputField))
                        .addGap(29, 29, 29)
                        .addComponent(jRemainingLettersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(jAlphabetLabel)
                .addGap(18, 18, 18)
                .addComponent(jExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpInstructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpInstructionsButtonActionPerformed
        InstructionsFrame instructionsFrame = new InstructionsFrame();
        instructionsFrame.setVisible(true);
    }//GEN-LAST:event_jpInstructionsButtonActionPerformed

    private void jExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButtonActionPerformed
        this.dispose(); //exit the game
    }//GEN-LAST:event_jExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAlphabetLabel;
    private javax.swing.JLabel jEnterLetterLabel;
    private javax.swing.JButton jExitButton;
    private javax.swing.JTextArea jGallowsArea;
    private javax.swing.JLabel jGuessWordLabel;
    private javax.swing.JTextField jLetterInputField;
    private javax.swing.JLabel jMysteryWordDiisplayLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jRemainingLettersLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSubmitLetterButton;
    private javax.swing.JButton jpInstructionsButton;
    private javax.swing.JLabel jpTitle;
    // End of variables declaration//GEN-END:variables
}
