/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wddbyui.cit260.hangman.frames;

/**
 *
 * @author gerrygj
 */
public class GetNamesFrame extends javax.swing.JFrame {

    //private PlayerName playerName = new PlayerName();
    
    /**
     * Creates new form GetNamesFrame
     */
    public GetNamesFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGetNamePanel = new javax.swing.JPanel();
        jNameLabel = new javax.swing.JLabel();
        jNameTextField = new javax.swing.JTextField();
        jNameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jGetNamePanel.setBackground(new java.awt.Color(204, 204, 255));
        jGetNamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 66, 166), 2, true));

        jNameLabel.setFont(new java.awt.Font("Minion Pro", 0, 24)); // NOI18N
        jNameLabel.setForeground(new java.awt.Color(61, 61, 155));
        jNameLabel.setText("Please enter your name:");

        jNameTextField.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N

        jNameButton.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        jNameButton.setText("Submit");
        jNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jGetNamePanelLayout = new javax.swing.GroupLayout(jGetNamePanel);
        jGetNamePanel.setLayout(jGetNamePanelLayout);
        jGetNamePanelLayout.setHorizontalGroup(
            jGetNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGetNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jGetNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jNameLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jGetNamePanelLayout.createSequentialGroup()
                        .addComponent(jNameTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jNameButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jGetNamePanelLayout.setVerticalGroup(
            jGetNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGetNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jGetNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jGetNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jGetNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetNamesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetNamesFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jGetNamePanel;
    private javax.swing.JButton jNameButton;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextField jNameTextField;
    // End of variables declaration//GEN-END:variables
}
