/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package wddbyui.cit260.hangman.frames;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gerrygj
 */
public class WinGameFrame extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form WinGameFrame
     */
    public WinGameFrame() {
        initComponents();
        this.jGallowsArea.setText(GameFrame.getGallowsString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jWinnerPanel = new javax.swing.JPanel();
        jPlayAgainButton = new javax.swing.JButton();
        jExitButton1 = new javax.swing.JButton();
        jWinnerLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGallowsArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jWinnerPanel.setBackground(new java.awt.Color(204, 204, 255));

        jPlayAgainButton.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        jPlayAgainButton.setText("Play Again");
        jPlayAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPlayAgainButtonActionPerformed(evt);
            }
        });

        jExitButton1.setFont(new java.awt.Font("Myriad Web Pro", 0, 16)); // NOI18N
        jExitButton1.setText("Exit Game");
        jExitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitButton1ActionPerformed(evt);
            }
        });

        jWinnerLabel.setBackground(new java.awt.Color(204, 204, 255));
        jWinnerLabel.setFont(new java.awt.Font("Minion Pro SmBd", 0, 36)); // NOI18N
        jWinnerLabel.setForeground(new java.awt.Color(61, 61, 155));
        jWinnerLabel.setText("Congratulations, You Win!");

        jGallowsArea.setEditable(false);
        jGallowsArea.setBackground(new java.awt.Color(255, 247, 222));
        jGallowsArea.setColumns(20);
        jGallowsArea.setFont(new java.awt.Font("Myriad Pro", 0, 14)); // NOI18N
        jGallowsArea.setRows(5);
        jGallowsArea.setText("                       ______________\n                       |                              |\n                       |                              |\n                       |                              |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n                       |\n          ______|______________\n   ___|                                             |\n   |                                                    | ");
        jGallowsArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 166), 3));
        jScrollPane1.setViewportView(jGallowsArea);

        javax.swing.GroupLayout jWinnerPanelLayout = new javax.swing.GroupLayout(jWinnerPanel);
        jWinnerPanel.setLayout(jWinnerPanelLayout);
        jWinnerPanelLayout.setHorizontalGroup(
            jWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jWinnerPanelLayout.createSequentialGroup()
                .addGroup(jWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jWinnerPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jWinnerLabel)
                            .addGroup(jWinnerPanelLayout.createSequentialGroup()
                                .addComponent(jPlayAgainButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jExitButton1))))
                    .addGroup(jWinnerPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jWinnerPanelLayout.setVerticalGroup(
            jWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jWinnerPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jWinnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jWinnerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlayAgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jWinnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jWinnerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jExitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jExitButton1ActionPerformed

    private void jPlayAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPlayAgainButtonActionPerformed
        GameFrame gameFrame = null;
        try {
            gameFrame = new GameFrame();
        } catch (IOException ex) {
            Logger.getLogger(LoseGameFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        gameFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPlayAgainButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinGameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinGameFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jExitButton1;
    private javax.swing.JTextArea jGallowsArea;
    private javax.swing.JButton jPlayAgainButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jWinnerLabel;
    private javax.swing.JPanel jWinnerPanel;
    // End of variables declaration//GEN-END:variables
}
